name: CI

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10"

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Show directories
        run: |
          echo "== .build =="
          find ".build" -maxdepth 2 
          echo ""
          echo "== build =="
          find build -type f -exec file {} \;

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-files
          path: |
            build/test-coverage.json
            build/test-execution.log
            build/test-report.xml
