name: CI

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10"

      - name: Build
        run: make build

      - name: Test
        run: make test
